[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.indexer"

[deploy]
startCommand = "./omnipair-carbon-indexer"
restartPolicyType = "always"
numReplicas = 1

[env]
RUST_LOG = "info"
RUST_BACKTRACE = "1" 
HEALTH_PORT = "8080"
WEBSOCKET_PORT = "8081"
