[build]
builder = "dockerfile"
dockerfilePath = "../Dockerfile.indexer"

[deploy]
startCommand = "./omnipair-carbon-indexer"
restartPolicyType = "always"
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 30
healthcheckPort = 8080
healthcheckStartPeriod = 60

[env]
RUST_LOG = "info"
RUST_BACKTRACE = "1"
HEALTH_PORT = "8080"
